### ISSUE TITLE
TSN performance is way too bad

### ISSUE THREAD

**Issue by gongbudaizhe** [coderSkyChen/Action_Recognition_Zoo#1]
Hi,

The prec@1 of the TSN-RGB model is way too bad. In my experiments, it should be around 17%. Please check it by using the TSN authors' repository instead: https://github.com/yjxiong/tsn-pytorch

**Comment by coderSkyChen** [comment]
Hi，thanks for your issue, however i've been busy these days, i'll address it before the end of this year.
